#define ST_PRES_SENSOR_CBOX     100
#define INTENS_ARM_LS_EBOX      101
#define INTENS_ARM_PRES_EBOX    102

#define PRES_LOOP_GAIN_EBOX     103
#define PRES_LOOP_TIME_EBOX     104
#define IDC_MSCTLS_UPDOWN1	117

#define END_TIME_1_EBOX         105
#define END_TIME_2_EBOX         106
#define END_TIME_3_EBOX         107

#define PRES_1_EBOX             108
#define PRES_2_EBOX             109
#define PRES_3_EBOX             110

#define PACCEL_1_EBOX           111
#define PACCEL_2_EBOX           112
#define PACCEL_3_EBOX           113

#define ST_EOS_PRESSURE_EBOX    114
#define ST_EOS_VELOCITY_EBOX    115
#define ST_MIN_STROKE_EBOX      116

#define LS1_NAME_EBOX           100
#define LS2_NAME_EBOX           101
#define LS3_NAME_EBOX           102
#define LS4_NAME_EBOX           103
#define LS5_NAME_EBOX           104

#define VAC_1_RADIO             105
#define VAC_2_RADIO             106
#define VAC_3_RADIO             107
#define VAC_4_RADIO             108
#define VAC_5_RADIO             109

#define BREAK_GAIN_1_EBOX       124
#define BREAK_GAIN_2_EBOX       125
#define BREAK_GAIN_3_EBOX       126
#define BREAK_VEL_1_EBOX        127
#define BREAK_VEL_2_EBOX        128
#define BREAK_VEL_3_EBOX        129
#define FT_STOP_POS_EBOX        130
#define VEL_LOOP_GAIN_EBOX      131
#define SURETRAK_PARAMETERS_OK  132
#define VARIABLE_NUMBER_LISTBOX 133
#define SUB_EBOX                134
#define MUL_EBOX                135
#define DIV_EBOX                136
#define ADD_EBOX                137
#define POS_RADIO               138
#define VEL_RADIO               139
#define VOLT_RADIO              140
#define PRES_RADIO              141
#define OTHER_RADIO             142
#define GPV_DESC_EBOX           143
#define VALUE_EBOX              144
#define ACCEL_1_EDITBOX         146
#define VEL_1_EDITBOX           147
#define EP_1_EDITBOX            148
#define VW_1_CHECKBOX           149
#define LI_1_EDITBOX            150
#define LIFI_1_CHECKBOX         151
#define ACCEL_2_EDITBOX         152
#define VEL_2_EDITBOX           153
#define EP_2_EDITBOX            154
#define VW_2_CHECKBOX           155
#define LI_2_EDITBOX            156
#define LIFI_2_CHECKBOX         157
#define ACCEL_3_EDITBOX         158
#define VEL_3_EDITBOX           159
#define EP_3_EDITBOX            160
#define VW_3_CHECKBOX           161
#define LI_3_EDITBOX            162
#define LIFI_3_CHECKBOX         163
#define ACCEL_4_EDITBOX         164
#define VEL_4_EDITBOX           165
#define EP_4_EDITBOX            166
#define VW_4_CHECKBOX           167
#define LI_4_EDITBOX            168
#define LIFI_4_CHECKBOX         169
#define ACCEL_5_EDITBOX         170
#define VEL_5_EDITBOX           171
#define EP_5_EDITBOX            172
#define VW_5_CHECKBOX           173
#define LI_5_EDITBOX            174
#define LIFI_5_CHECKBOX         175
#define ACCEL_6_EDITBOX         176
#define VEL_6_EDITBOX           177
#define EP_6_EDITBOX            178
#define VW_6_CHECKBOX           179
#define LI_6_EDITBOX            180
#define LIFI_6_CHECKBOX         181
#define LS1_EDITBOX             182
#define LS2_EDITBOX             183
#define LS3_EDITBOX             184
#define LS4_EDITBOX             185
#define LS5_EDITBOX             186
#define LS1_DESC_TBOX           187
#define LS2_DESC_TBOX           188
#define LS3_DESC_TBOX           189
#define LS4_DESC_TBOX           190
#define LS5_DESC_TBOX           191
#define ST_TAB_CONTROL          192
#define VELOCITY_CONTROL_BUTTON 193
#define GP_VARIABLE_BUTTON      194
#define SAVE_CHANGES_BUTTON     195

/*
-------
Strings
------- */
#define FIRST_TAB_STRING                   1
#define VELOCITY_CONTROL_TAB_STRING        1
#define PRESSURE_CONTROL_TAB_STRING        2
#define GP_VARIABLE_TAB_STRING             3

/*
------------
Accelerators
------------ */
#define TAB_KEY                         901
#define SHIFT_TAB_KEY                   902

