#define EXPORT_TAB_CONTROL              1000
#define SET_START_BUTTON                1001
#define SET_END_BUTTON                  1002
#define EXPORT_BUTTON                   1003
#define DELETE_BUTTON                   1004
#define SELECT_ALL_BUTTON               1005
#define START_CHOICE_TBOX               1006
#define END_CHOICE_TBOX                 1007
#define EXPORT_LISTBOX                  1008

/*
-------
Strings
------- */
#define FIRST_TAB_STRING                   1
#define PARAMETER_TAB_STRING               1
#define DOWNTIME_TAB_STRING                2
#define ALARM_SUMMARY_TAB_STRING           3
#define TAB_COUNT                          3

