#include <windows.h>

#include "UGCtrl.h"

/***********************************************************************
*                          CUGCellFormat                               *
************************************************************************/
CUGCellFormat::CUGCellFormat()
{
}

/***********************************************************************
*                         ~CUGCellFormat                               *
************************************************************************/
CUGCellFormat::~CUGCellFormat()
{
}

/***********************************************************************
*                       ApplyDisplayFormat                             *
************************************************************************/
void CUGCellFormat::ApplyDisplayFormat( CUGCell * cell )
{
}

/***********************************************************************
*                       ValidateDisplayFormat                          *
*  return   0 - information valid                                      *
*           1 - information invalid                                    *
************************************************************************/
int CUGCellFormat::ValidateCellInfo( CUGCell * cell )
{
return 0;
}
