del /Q bupres\udebug\*.*
del /Q bupres\ufree\*.*
del /Q copylog\ufree\*.*
del /Q downtime\ufree\*.*
del /Q dundas\udebug\*.*
del /Q dundas\ufree\*.*
del /Q editdown\udebug\*.*
del /Q editdown\ufree\*.*
del /Q editpart544\udebug\*.*
del /Q editpart544\ufree\*.*
del /Q emachine\ufree\*.*
del /Q emachine\udebug\*.*
del /Q esensor\udebug\*.*
del /Q esensor\ufree\*.*
del /Q eventman\ufree\*.*
del /Q fastrak\udebug\*.*
del /Q fastrak\ufree\*.*
del /Q ft2\ufree\*.*
del /Q ftclasnt\udebug\*.*
del /Q ftclasnt\ufree\*.*
del /Q install\ufree\*.*
del /Q monall\udebug\*.*
del /Q monall\ufree\*.*
del /Q monedit\udebug\*.*
del /Q monedit\ufree\*.*
del /Q profile\udebug\*.*
del /Q profile\ufree\*.*
del /Q startup\ufree\*.*
del /Q stddown\ufree\*.*
del /Q subs\udebug\*.*
del /Q subs\ufree\*.*
del /Q suretrak544\ufree\*.*
del /Q terminal\ufree\*.*
del /Q v5setups\udebug\*.*
del /Q v5setups\ufree\*.*
del /Q visiedit\ufree\*.*
del /Q vtextrac\ufree\*.*
