#define MINIMIZE_MENU_CHOICE               103
#define EXIT_MENU_CHOICE                   108
#define SHOW_CURRENT_FT_VALUES_MENU_CHOICE 501
#define IOEX4_MENU_CHOICE                  502
#define HELP_CONTENTS_MENU_CHOICE          701

#define PROM_VERSION_STRING             9
#define CREATE_FAILED_STRING            10
#define UNABLE_TO_CONTINUE_STRING       13
#define TESTING_RAM_STRING              47
#define NO_RAM_ERRORS_STRING            48
#define HIGH_RAM_ERROR_STRING           49
#define LOW_RAM_ERROR_STRING            50
#define TESTING_OPTO_PORT_STRING        51
#define OPTO_PORT_OK_STRING             52
#define OPTO_PORT_ERROR_STRING          53
#define TESTING_IO_PORT_STRING          54
#define IO_PORT_OK_STRING               55
#define IO_PORT_DATA_ERROR_STRING       56
#define IO_PORT_COMMAND_ERROR_STRING    57
#define SKIP_COUNT_STRING               58
#define SKIP_SECONDS_STRING             59
#define SHOTSAVE_WAIT_FAIL_STRING       60
#define SHOTSAVE_EVENT_FAIL_STRING      61
#define BOARD_MONITOR_EVENT_FAIL_STRING 62
#define BOARD_MONITOR_THREAD_STRING     63
#define SHOTSAVE_THREAD_STRING          64
#define CREATE_PIPE_FAILED_STRING       65
#define LOW_DISK_SPACE_STRING           66
#define NO_SHOTS_SAVED_STRING           67
#define ON_1_STRING                     68
#define OFF_1_STRING                    69
#define ON_2_STRING                     70
#define OFF_2_STRING                    71
#define ON_3_STRING                     72
#define OFF_3_STRING                    73
#define ON_4_STRING                     74
#define OFF_4_STRING                    75
#define CANT_COMPLY_STRING              76
#define NEED_CMD_MODE_STRING            77
#define MUX_BOARD_ONLY_STRING           78
#define MONITORING_STRING               79
#define NOT_MONITORING_STRING           80
#define SET_DATA_COL_MODE_STRING        81
#define ERROR_STRING                    82
#define SET_COMMAND_MODE_STRING         83
#define MONITOR_WINDOW_TITLE_STRING     84
#define BOARD_NOT_STARTED_STRING        85
#define ERROR_IN_COMMUNICATION_STRING   86
#define UNABLE_TO_SET_MONITOR_WIRE_STRING 87
#define MORE_THAN_ONE_MACHINE_STRING    88
#define NO_CURRENT_PART_STRING          89
#define WIRE_USED_BY_ALARM_STRING       90
#define INVALID_WIRE_STRING             91
#define UNABLE_TO_SET_DOWN_ALARM_WIRE_STRING 92
#define FT_BOARD_STRING                 93
#define AT_ADDRESS_STRING               94
#define BOARD_TYPE_ERR_STRING           95
#define COMMAND_MODE_ERR_STRING         96
#define NO_BOARD_INIT_STRING            97

#define AUTO_SHOT_MACHINE_NUMBER_TEXTBOX 100
#define SCAN_MODE_BIT_TBOX              101
#define SAVE_TOTAL_STROKE_XBOX          101
#define CHAN_1_XDCR_CBOX                101
#define UNITS_AND_PITCH_LISTBOX         101
#define MINIMIZE_SCREEN_MENU            101
#define VARIABLE_NUMBER_EBOX            101
#define READ_DATA_PORT_BUTTON           101
#define SAVE_VALVE_TEST_MASTER_BUTTON   101
#define PARAMETERS_BUTTON               101
#define FT_RAM_DATA_LISTBOX             101
#define SHOT_PARAM_LISTBOX              101
#define NEW_SAMPLE_BUTTON               101
#define EPROM_NUMBER_TBOX               101
#define AUTO_SHOT_LABEL_TBOX            101
#define BIT_2_TBOX                      102
#define SAVE_MINIMUM_STROKE_XBOX        102
#define CHAN_2_XDCR_CBOX                102
#define EXIT_TASK_MENU                  102
#define VARIABLE_VALUE_EBOX             102
#define SEND_DATA_PORT_BUTTON           102
#define RESTART_BUTTON                  102
#define CURRENT_PARAMETER_VALUE_LISTBOX 102
#define CHANNEL_FRAME                   102
#define PARAM_CALC_ERROR_BIT_TBOX       103
#define SAVE_ZERO_SPEED_CHECK_XBOX      103
#define CHAN_3_XDCR_CBOX                103
#define READ_VARIABLE_BUTTON            103
#define DATA_PORT_VALUE_EBOX            103
#define NULL_VALVE_BUTTON               103
#define INVALID_COMMAND_BIT_TBOX        104
#define TOTAL_STROKE_EBOX               104
#define CHAN_4_XDCR_CBOX                104
#define SET_VARIABLE_BUTTON             104
#define VALVE_TEST_BUTTON               104
#define INTERNAL_ERROR_BIT_TBOX         105
#define MINIMUM_STROKE_EBOX             105
#define CHAN_5_XDCR_CBOX                105
#define TRANSDUCER_TEST_BUTTON          105
#define MEM_SELF_TEST_ERROR_BIT_TBOX    106
#define ZERO_SPEED_CHECK_EBOX           106
#define CHAN_6_XDCR_CBOX                106
#define SERVICE_TOOLS_BUTTON            106
#define XDCR_ERROR_BIT_TBOX             107
#define CHAN_7_XDCR_CBOX                107
#define PUMP_ON_RADIO                   107
#define CYCLE_START_TIMEOUT_BIT_TBOX    108
#define CHAN_8_XDCR_CBOX                108
#define START_SHOT_RADIO                108
#define NO_INTERRUPTS_BIT_TBOX          109
#define ALL_VOLTS_BUTTON                109
#define FOLLOW_THROUGH_RADIO            109
#define MAX_POSITION_RESET_BUTTON       109
#define POWER_UP_BIT_TBOX               110
#define CHAN_1_GAIN_1_RADIO             110
#define RETRACT_RADIO                   110
#define SAVE_TOTAL_STROKE_BUTTON        110
#define CYCLE_START_BIT_TBOX            111
#define CHAN_1_GAIN_2_RADIO             111
#define CLEAR_COMMAND_PORT_BUTTON       111
#define JOG_SHOT_RADIO                  111
#define UNITS_1_TBOX                    111
#define DATA_READY_BIT_TBOX             112
#define CHAN_2_GAIN_1_RADIO             112
#define SEND_COMMAND_BUTTON             112
#define MANUAL_RADIO                    112
#define UNITS_2_TBOX                    112
#define ZERO_SPEED_BIT_TBOX             113
#define CHAN_2_GAIN_2_RADIO             113
#define COMMAND_VALUE_EBOX              113
#define AT_HOME_RADIO                   113
#define UNITS_3_TBOX                    113
#define DATA_COLLECTION_BIT_TBOX        114
#define CHAN_3_GAIN_1_RADIO             114
#define OK_FOR_VAC_FAST_RADIO           114
#define UNITS_4_TBOX                    114
#define ERROR_BIT_TBOX                  115
#define CHAN_3_GAIN_2_RADIO             115
#define VACUUM_ON_RADIO                 115
#define UNITS_5_TBOX                    115
#define BUSY_BIT_TBOX                   116
#define CHAN_4_GAIN_1_RADIO             116
#define LOW_IMPACT_RADIO                116
#define UNITS_6_TBOX                    116
#define CHAN_4_GAIN_2_RADIO             117
#define FILL_TEST_RADIO                 117
#define UNITS_7_TBOX                    117
#define CHAN_5_GAIN_1_RADIO             118
#define E_STOP_RADIO                    118
#define UNITS_8_TBOX                    118
#define CHAN_5_GAIN_2_RADIO             119
#define SLOW_SHOT_OUTPUT_RADIO          119
#define RESET_FT_POSITION_BUTTON        119
#define CHAN_6_GAIN_1_RADIO             120
#define CLEAR_DATA_READY_BUTTON         120
#define ACCUMULATOR_RADIO               120
#define CHAN_6_GAIN_2_RADIO             121
#define READ_SHOT_PARAM_BUTTON          121
#define LS1_RADIO                       121
#define CHAN_7_GAIN_1_RADIO             122
#define READ_RAM_BUTTON                 122
#define LS2_RADIO                       122
#define CHAN_7_GAIN_2_RADIO             123
#define AUTO_COLLECTION_BUTTON          123
#define LS3_RADIO                       123
#define CHAN_8_GAIN_1_RADIO             124
#define ENABLE_INPUT_POS_CHECK_XBOX     124
#define LS4_RADIO                       124
#define CHAN_8_GAIN_2_RADIO             125
#define LATCH_SHOT_COUNTERS_BUTTON      125
#define CURRENT_MAIN_POSITION_TEXTBOX   125
#define CLEAR_SHOT_COUNTERS_BUTTON      126
#define CURRENT_VALVE_COMMAND_TEXTBOX   126
#define SET_SCAN_MODE_BUTTON            127
#define CONTROL_ACTIVE_TEXTBOX          127
#define WAITING_FOR_TEXTBOX             128
#define SET_ANALOG_XDCR_TYPE_BUTTON     129
#define MAIN_PROGRAM_STATUS_TEXTBOX     129
#define SET_UNITS_AND_PITCH_BUTTON      130
#define BLOCK_NUMBER_TEXTBOX            130
#define CONTROL_DISABLED_STATUS_TEXTBOX 131
#define BUSY_STATUS_TEXTBOX             132
#define FATAL_ERROR_STATUS_TEXTBOX      133
#define WARNING_STATUS_TEXTBOX          134
#define SHOT_IN_PROGRESS_STATUS_TEXTBOX 135
#define BIT_11_STATUS_TEXTBOX           136
#define POWER_UP_STATUS_TEXTBOX         137
#define INT_DISABLED_STATUS_TEXTBOX     138
#define BIT_8_STATUS_TEXTBOX            139
#define BOARD_1_RADIO                   140
#define POS_XDCR_WARNING_STATUS_TEXTBOX 140
#define BOARD_2_RADIO                   141
#define MEMORY_ERROR_STATUS_TEXTBOX     141
#define BOARD_3_RADIO                   142
#define INTERNAL_ERROR_STATUS_TEXTBOX   142
#define BOARD_4_RADIO                   143
#define INVALID_COMMAND_STATUS_TEXTBOX  143
#define BOARD_5_RADIO                   144
#define BIT_2_STATUS_TEXTBOX            144
#define BOARD_6_RADIO                   145
#define BIT_1_STATUS_TEXTBOX            145
#define BOARD_7_RADIO                   146
#define DOWNLOAD_BUTTON                 146
#define BOARD_8_RADIO                   147
#define BOARD_ADDRESS_EBOX              150
#define MACHINE_NAME_TBOX               150
#define SINGLE_BOARD_XBOX               151
#define COMPUTER_NAME_TBOX              151
#define MUX_BOARD_XBOX                  152
#define PART_NAME_TBOX                  152
#define FOUR_MHZ_BOARD_RADIO            153
#define MAIN_POSITION_UNITS_TBOX        153
#define TWELVE_MHZ_BOARD_RADIO          154
#define MUX_CHANNEL_1_RADIO             160
#define TAB_KEY                         160
#define MUX_CHANNEL_2_RADIO             161
#define MUX_CHANNEL_3_RADIO             162
#define MUX_CHANNEL_4_RADIO             163
#define MUX_CHANNEL_5_RADIO             164
#define MUX_CHANNEL_6_RADIO             165
#define MUX_CHANNEL_7_RADIO             166
#define MUX_CHANNEL_8_RADIO             167
#define SET_DATA_COLL_MODE_BUTTON       170
#define XDCR_TEST_BUTTON                171
#define SET_COMMAND_MODE_BUTTON         172
#define GET_PROM_VERSION_BUTTON         173
#define READ_CURRENT_VALUES_BUTTON      174
#define COMMAND_AND_DATA_PORTS_BUTTON   175
#define SETUP_PARAMS_BUTTON             177
#define CLEAR_ERROR_STATUS_BUTTON       178
#define TEST_RAM_BUTTON                 179
#define TEST_OPTO_BUTTON                180
#define TEST_IO_BUTTON                  181
#define MUX_ENABLE_1_XBOX               190
#define MUX_ENABLE_2_XBOX               191
#define MUX_ENABLE_3_XBOX               192
#define MUX_ENABLE_4_XBOX               193
#define MUX_ENABLE_5_XBOX               194
#define MUX_ENABLE_6_XBOX               195
#define MUX_ENABLE_7_XBOX               196
#define MUX_ENABLE_8_XBOX               197
#define TOTAL_STROKE_LENGTH_EBOX        200
#define FASTRAK_STATUS_TBOX             200
#define MIN_STROKE_LENGTH_EBOX          201
#define IOEX4_MACHINE_TBOX              201
#define PRE_IMPACT_RADIO                201
#define FT_CURRENT_VELOCITY_TBOX        201
#define TIME_DELAY_BISCUIT_EBOX         202
#define IOEX4_PART_TBOX                 202
#define POST_IMPACT_RADIO               202
#define FT_CURRENT_POSITION_TBOX        202
#define VEL_FOR_EOS_EBOX                203
#define IOEX4_COMPUTER_TBOX             203
#define RAW_HEX_RADIO                   203
#define VELOCITY_UNITS_TBOX             203
#define FILL_DISTANCE_EBOX              204
#define CONVERTED_RADIO                 204
#define POSITION_UNITS_TBOX             204
#define RUNNER_FILL_DISTANCE_EBOX       205
#define VOLTS_RADIO                     205
#define MAX_POSITION_TBOX               205
#define VEL_FOR_CSFS_EBOX               206
#define VEL_FOR_RISE_TIME_EBOX          207
#define MIN_POS_FOR_CSFS_EBOX           208
#define NOF_TIME_POINTS_EBOX            209
#define TIME_BASED_MS_EBOX              210
#define OPTO_BIT_0_XBOX                 210
#define VOLTS_1_TBOX                    210
#define CYCLE_START_TIMEOUT_EBOX        211
#define OPTO_BIT_1_XBOX                 211
#define VOLTS_2_TBOX                    211
#define MIN_EOS_EBOX                    212
#define OPTO_BIT_2_XBOX                 212
#define VOLTS_3_TBOX                    212
#define OPTO_BIT_3_XBOX                 213
#define VOLTS_4_TBOX                    213
#define OPTO_BIT_4_XBOX                 214
#define VOLTS_5_TBOX                    214
#define OPTO_BIT_5_XBOX                 215
#define VOLTS_6_TBOX                    215
#define OPTO_BIT_6_XBOX                 216
#define VOLTS_7_TBOX                    216
#define OPTO_BIT_7_XBOX                 217
#define VOLTS_8_TBOX                    217
#define TOTAL_STROKE_UNITS_TBOX         220
#define MIN_STROKE_UNITS_TBOX           221
#define VEL_FOR_EOS_UNITS_TBOX          222
#define FILL_DISTANCE_UNITS_TBOX        223
#define RUNNER_FILL_UNITS_TBOX          224
#define VEL_FOR_CSFS_UNITS_TBOX         225
#define VEL_FOR_RISE_UNITS_TBOX         226
#define MIN_CSFS_POS_UNITS_TBOX         227
#define MIN_EOS_UNITS_TBOX              228

#define LS1_SETPOINT_EBOX               240
#define LS2_SETPOINT_EBOX               241
#define LS3_SETPOINT_EBOX               242
#define LS4_SETPOINT_EBOX               243
#define LS1_SETPOINT_UNITS_TBOX         244
#define LS2_SETPOINT_UNITS_TBOX         245
#define LS3_SETPOINT_UNITS_TBOX         246
#define LS4_SETPOINT_UNITS_TBOX         247

#define ANALOG_1_XBOX                   101
#define ANALOG_2_XBOX                   102
#define ANALOG_3_XBOX                   103
#define ANALOG_4_XBOX                   104
#define ANALOG_5_XBOX                   105
#define ANALOG_6_XBOX                   106
#define ANALOG_7_XBOX                   107
#define ANALOG_8_XBOX                   108

/*
------------------------
FT_CURRENT_VALUES_DIALOG
------------------------ */
#define ANALOG_1_TBOX                   101
#define ANALOG_2_TBOX                   102
#define ANALOG_3_TBOX                   103
#define ANALOG_4_TBOX                   104
#define ANALOG_5_TBOX                   105
#define ANALOG_6_TBOX                   106
#define ANALOG_7_TBOX                   107
#define ANALOG_8_TBOX                   108

#define FT_POS_THERM                    228
#define FT_VEL_THERM                    229
#define FT_A1_THERM                     230
#define FT_A2_THERM                     231
#define FT_A3_THERM                     232
#define FT_A4_THERM                     233
#define FT_A5_THERM                     234
#define FT_A6_THERM                     235
#define FT_A7_THERM                     236
#define FT_A8_THERM                     237

#define FT_A1_XBOX                      220
#define FT_A2_XBOX                      221
#define FT_A3_XBOX                      222
#define FT_A4_XBOX                      223
#define FT_A5_XBOX                      224
#define FT_A6_XBOX                      225
#define FT_A7_XBOX                      226
#define FT_A8_XBOX                      227

#define CSV_ENABLE_XBOX                 300
#define CSV_FILE_NAME_EBOX              301
#define CSV_CHANNEL_EBOX                302

/*
-------------------------
NO_POSITION_SENSOR_DIALOG
------------------------- */
#define ROD_PITCH_TBOX           100
#define CLOCK_SPEED_TBOX         101
#define DISTANCE_UNITS_TBOX      102
#define NPS_VELOCITY_UNITS_TBOX  103

