//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by JeditRes.rc
//
#define VELOCITY_UNITS_TBOX             165
#define FT_CURRENT_VELOCITY_TBOX        166
#define FT_CURRENT_POSITION_TBOX        167
#define FT_ANALOG_1_TBOX                174
#define FT_ANALOG_2_TBOX                175
#define FT_ANALOG_3_TBOX                176
#define FT_ANALOG_4_TBOX                177
#define FT_ANALOG_5_TBOX                178
#define FT_ANALOG_6_TBOX                179
#define FT_ANALOG_7_TBOX                180
#define FT_ANALOG_8_TBOX                181
#define POSITION_UNITS_TBOX             182
#define FT_INPUT_BIT_01                 201
#define FT_INPUT_BIT_02                 202
#define FT_INPUT_BIT_03                 203
#define FT_INPUT_BIT_04                 204
#define FT_INPUT_BIT_05                 205
#define FT_INPUT_BIT_06                 206
#define FT_INPUT_BIT_07                 207
#define FT_INPUT_BIT_08                 208
#define FT_INPUT_BIT_09                 209
#define FT_INPUT_BIT_10                 210
#define FT_INPUT_BIT_11                 211
#define FT_INPUT_BIT_12                 212
#define FT_INPUT_BIT_13                 213
#define FT_INPUT_BIT_14                 214
#define FT_INPUT_BIT_15                 215
#define FT_INPUT_BIT_16                 216
#define FT_OUTPUT_BIT_01                221
#define FT_OUTPUT_BIT_02                222
#define FT_OUTPUT_BIT_03                223
#define FT_OUTPUT_BIT_04                224
#define FT_OUTPUT_BIT_05                225
#define FT_OUTPUT_BIT_06                226
#define FT_OUTPUT_BIT_07                227
#define FT_OUTPUT_BIT_08                228
#define FT_OUTPUT_BIT_09                229
#define FT_OUTPUT_BIT_10                230
#define FT_OUTPUT_BIT_11                231
#define FT_OUTPUT_BIT_12                232
#define FT_OUTPUT_BIT_13                233
#define FT_OUTPUT_BIT_14                234
#define FT_OUTPUT_BIT_15                235
#define FT_OUTPUT_BIT_16                236
#define FT_STATUS_BIT_01                241
#define FT_STATUS_BIT_02                242
#define FT_STATUS_BIT_03                243
#define FT_STATUS_BIT_04                244
#define FT_STATUS_BIT_05                245
#define FT_STATUS_BIT_06                246
#define FT_STATUS_BIT_07                247
#define FT_STATUS_BIT_08                248
#define FT_STATUS_BIT_09                249
#define FT_STATUS_BIT_10                250
#define FT_STATUS_BIT_11                251
#define FT_STATUS_BIT_12                252
#define FT_STATUS_BIT_13                253
#define FT_STATUS_BIT_14                254
#define FT_STATUS_BIT_15                255
#define FT_STATUS_BIT_16                256
#define ST_INPUT_BIT_01                 301
#define ST_INPUT_BIT_02                 302
#define ST_INPUT_BIT_03                 303
#define ST_INPUT_BIT_04                 304
#define ST_INPUT_BIT_05                 305
#define ST_INPUT_BIT_06                 306
#define ST_INPUT_BIT_07                 307
#define ST_INPUT_BIT_08                 308
#define ST_INPUT_BIT_09                 309
#define ST_INPUT_BIT_10                 310
#define ST_INPUT_BIT_11                 311
#define ST_INPUT_BIT_12                 312
#define ST_INPUT_BIT_13                 313
#define ST_INPUT_BIT_14                 314
#define ST_INPUT_BIT_15                 315
#define ST_INPUT_BIT_16                 316
#define ST_OUTPUT_BIT_01                321
#define ST_OUTPUT_BIT_02                322
#define ST_OUTPUT_BIT_03                323
#define ST_OUTPUT_BIT_04                324
#define ST_OUTPUT_BIT_05                325
#define ST_OUTPUT_BIT_06                326
#define ST_OUTPUT_BIT_07                327
#define ST_OUTPUT_BIT_08                328
#define ST_OUTPUT_BIT_09                329
#define ST_OUTPUT_BIT_10                330
#define ST_OUTPUT_BIT_11                331
#define ST_OUTPUT_BIT_12                332
#define ST_OUTPUT_BIT_13                333
#define ST_OUTPUT_BIT_14                334
#define ST_OUTPUT_BIT_15                335
#define ST_OUTPUT_BIT_16                336
#define ST_STATUS_BIT_01                341
#define ST_STATUS_BIT_02                342
#define ST_STATUS_BIT_03                343
#define ST_STATUS_BIT_04                344
#define ST_STATUS_BIT_05                345
#define ST_STATUS_BIT_06                346
#define ST_STATUS_BIT_07                347
#define ST_STATUS_BIT_08                348
#define ST_STATUS_BIT_09                349
#define ST_STATUS_BIT_10                350
#define ST_STATUS_BIT_11                351
#define ST_STATUS_BIT_12                352
#define ST_STATUS_BIT_13                353
#define ST_STATUS_BIT_14                354
#define ST_STATUS_BIT_15                355
#define ST_STATUS_BIT_16                356
#define ST_CURRENT_POSITION_TBOX        357
#define ST_CURRENT_DAC_TBOX             358
#define ST_CURRENT_VELOCITY_TBOX        359
#define FT_COMMAND_MODE_BUTTON          360
#define ST_ANALOG_1_TBOX                361
#define ST_ANALOG_2_TBOX                362
#define ST_ANALOG_3_TBOX                363
#define ST_ANALOG_4_TBOX                364
#define ST_CURRENT_BLOCK_TBOX           371
#define CC_STATUS_MESSAGE_TBOX          372
#define CC_ERROR_MESSAGE_TBOX           373
#define TRUE_STRIP_CHART_RADIO          374
#define ACTIVATE_CONTROL_BUTTON         400
#define RESTART_CONTROL_BUTTON          401
#define FT_POS_THERM                    1019
#define SURETRAK_STATUS_GROUPBOX        1022
#define FT_VEL_THERM                    1026
#define FT_A1_THERM                     1027
#define FT_A2_THERM                     1028
#define FT_A3_THERM                     1029
#define FT_A4_THERM                     1030
#define FT_A5_THERM                     1031
#define FT_A6_THERM                     1032
#define FT_A7_THERM                     1033
#define FT_A8_THERM                     1034
#define ST_POS_THERM                    1035
#define ST_VEL_THERM                    1036
#define ST_CV_THERM                     1037
#define ST_A1_THERM                     1038
#define FT_A1_XBOX                      1050
#define FT_A2_XBOX                      1051
#define FT_A3_XBOX                      1052
#define FT_A4_XBOX                      1053
#define FT_A5_XBOX                      1054
#define FT_A6_XBOX                      1055
#define FT_A7_XBOX                      1056
#define FT_A8_XBOX                      1057
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
