/*
-------
Strings
------- */
#define BEGIN_RESTORE_BUTTON             101
#define CHOOSE_FILES_BUTTON              107
#define RESTORE_FILES_LISTBOX            105
#define PURGE_BEFORE_RESTORE_RADIOBUTTON 102
#define MERGE_WITH_EXISTING_RADIOBUTTON  103
#define DS_STATUS_TBOX                   106

#define UNABLE_TO_CONTINUE_STRING   1
#define CREATE_FAILED_STRING        2
#define RESTORE_NOT_FOUND_STRING    3
#define GET_RESTORE_FAILED_STRING   4
#define DIR_CREATE_FAIL             5
#define CANT_DO_THAT_STRING         6
#define UNZIP_ERROR_STRING          7
#define MERGING_SHOT_STRING         8
#define COPY_COMPLETE_STRING        9
#define CREATING_NEW_MACHINE_STRING 10
#define CREATING_NEW_PART_STRING    11
#define BEGIN_RESTORE_STRING        12
#define ABORT_RESTORE_STRING        13
#define RESTORE_THREAD_STRING       14
#define UNABLE_TO_ALLOC_BUFFER_STRING 15
#define FILE_COMPLETE_STRING        16
#define MACHINE_CREATE_ERROR_STRING 17
#define PART_CREATE_ERROR_STRING    18
#define DEFAULT_PART_ERROR_STRING   19

#define MINIMIZE_MENU 107
#define EXIT_MENU     108
#define HELP_MENU     901
#define ABOUT_MENU    902

